CREATE TABLE EMPRESA(
	Nome VARCHAR(50) NOT NULL,
	NIF INT NOT NULL,
	CHECK ( NIF > 0 AND NIF < 99999999),
	PRIMARY KEY (NIF)
);

CREATE TABLE PRODUTO(
	Codigo INT NOT NULL,
	CHECK (CODIGO > 0),
	NIF_Empresa INT NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Taxa_IVA FLOAT NOT NULL,
	CHECK (Taxa_IVA > 0),
	Preco FLOAT NOT NULL,
	CHECK (Preco > 0),
	Stock INT NOT NULL,

	PRIMARY KEY (Codigo, NIF_Empresa),
	FOREIGN KEY (NIF_Empresa) REFERENCES EMPRESA(NIF)
);

CREATE TABLE TIPO_FORNECEDOR(
	Designacao VARCHAR(50) NOT NULL,
	Codigo_Interno INT NOT NULL,

	PRIMARY KEY (Codigo_Interno)
);

CREATE TABLE FORNECEDOR(
	NIF INT NOT NULL,
	Codigo_Interno INT NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	FAX VARCHAR(9) NOT NULL,
	Endereco VARCHAR(30) NOT NULL,
	Cond_Pagamento INT NOT NULL,
	
	PRIMARY KEY (NIF),
	FOREIGN KEY (Codigo_Interno) REFERENCES TIPO_FORNECEDOR(Codigo_Interno)
);

CREATE TABLE ENCOMENDA(
	Numero INT NOT NULL,
	NIF_Empresa INT NOT NULL,
	Data_Encomenda DATE NOT NULL,
	NIF_Fornecedor INT NOT NULL,

	PRIMARY KEY (Numero, NIF_Empresa, NIF_Fornecedor),
	FOREIGN KEY(NIF_Empresa) REFERENCES EMPRESA(NIF),
	FOREIGN KEY (NIF_Fornecedor) REFERENCES FORNECEDOR(NIF)
);

CREATE TABLE POSSUI(
	Stock INT NOT NULL,
	Numero_Encomenda INT NOT NULL,
	Codigo_Produto INT NOT NULL,
	NIF_Empresa INT NOT NULL,

	PRIMARY KEY (Numero_Encomenda, Codigo_Produto),
	FOREIGN KEY (Codigo_Produto, NIF_Empresa) REFERENCES PRODUTO(Codigo, NIF_Empresa)
);

CREATE TABLE FORNECE(
	NIF_Empresa INT NOT NULL,
	NIF_Fornecedor INT NOT NULL,
	PRIMARY KEY (NIF_Empresa, NIF_Fornecedor),
	FOREIGN KEY (NIF_Empresa) REFERENCES EMPRESA(NIF),
	FOREIGN KEY (NIF_Fornecedor) REFERENCES FORNECEDOR(NIF)
);