CREATE TABLE CLIENT(
	NIF INT NOT NULL,
	CHECK (NIF > 0 AND NIF < 999999999),
	Nome VARCHAR(40) NOT NULL,
	Endereco VARCHAR(100) NOT NULL,

	PRIMARY KEY (NIF),

);

CREATE TABLE BALCAO(
	Numero INT NOT NULL,
	Nome VARCHAR(40) NOT NULL,
	Endereco VARCHAR(100) NOT NULL,

	PRIMARY KEY (Numero),

);



CREATE TABLE TIPO_VEICULO(
	Codigo INT NOT NULL,
	Designacao VARCHAR(20) NOT NULL,
	Ar_condicionado INT NOT NULL,

	PRIMARY KEY (Codigo),
);

CREATE TABLE SIMILARIDADE(
	Codigo1 INT NOT NULL,
	Codigo2 INT NOT NULL,

	PRIMARY KEY (Codigo1, Codigo2),
	FOREIGN KEY (Codigo1) REFERENCES TIPO_VEICULO(Codigo),
	FOREIGN KEY (Codigo2) REFERENCES TIPO_VEICULO(Codigo),

);

CREATE TABLE LIGEIRO(
	Numero_Lugares INT NOT NULL,
	Portas INT NOT NULL,
	Combustivel VARCHAR(15) NOT NULL,
	Codigo INT NOT NULL,

	PRIMARY KEY (Codigo),
	FOREIGN KEY (Codigo) REFERENCES TIPO_VEICULO(Codigo),

);

CREATE TABLE PESADO(
	Passageiros INT NOT NULL,
	Peso FLOAT NOT NULL,
	Codigo INT NOT NULL,

	PRIMARY KEY (Codigo),
	FOREIGN KEY (Codigo) REFERENCES TIPO_VEICULO(Codigo),

);


CREATE TABLE VEICULO(
	Matricula VARCHAR(6) NOT NULL,
	Marca VARCHAR(20) NOT NULL,
	Ano INT NOT NULL,
	Tipo_Veiculo INT NOT NULL,

	PRIMARY KEY (Matricula),
	FOREIGN KEY (Tipo_Veiculo) REFERENCES TIPO_VEICULO(Codigo),

);

CREATE TABLE ALUGUER(
	Numero INT NOT NULL,
	Duracao INT NOT NULL,
	DataAluguer VARCHAR(10) NOT NULL,
	NIF_Client INT NOT NULL,
	Numero_Balcao INT NOT NULL,
	Matricula_Veiculo VARCHAR(6) NOT NULL,

	PRIMARY KEY (Numero),
	FOREIGN KEY (NIF_Client) REFERENCES CLIENT(NIF),
	FOREIGN KEY (Numero_Balcao) REFERENCES BALCAO(Numero),
	FOREIGN KEY (Matricula_Veiculo) REFERENCES VEICULO(Matricula),

);

