CREATE TABLE CONFERENCIA(
	ID INT NOT NULL,

	PRIMARY KEY (ID)
);


CREATE TABLE ARTIGO(
	Numero_Registo INT NOT NULL,
	Titulo VARCHAR(30) NOT NULL,

	PRIMARY KEY (Numero_Registo)
);

CREATE TABLE CONTEM(
	Email_Autor VARCHAR(50) NOT NULL,
	Num_Artigo INT NOT NULL,

	PRIMARY KEY (Email_Autor, Num_Artigo),
	FOREIGN KEY (Num_Artigo) REFERENCES ARTIGO(Numero_Registo)
);

CREATE TABLE APRESENTACAO(
	Conf_ID INT NOT NULL,
	Numero_Artigo INT NOT NULL,

	PRIMARY KEY (Conf_ID, Numero_Artigo),
	FOREIGN KEY (Conf_ID) REFERENCES CONFERENCIA(ID),
	FOREIGN KEY (Numero_Artigo) REFERENCES ARTIGO(Numero_Registo)
);

CREATE TABLE PARTICIPANTE(
	Email VARCHAR(50) NOT NULL,
	Data_Inscricao VARCHAR(10) NOT NULL,
	Morada VARCHAR(50) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Conf_ID INT NOT NULL,

	PRIMARY KEY (Email),
	FOREIGN KEY (Conf_ID) REFERENCES CONFERENCIA(ID)
);

CREATE TABLE NAO_ESTUDANTE(
	Email VARCHAR(50) NOT NULL,
	Data_Inscricao VARCHAR(10) NOT NULL,
	Morada VARCHAR(50) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Ref_Transacao VARCHAR(50) NOT NULL,

	PRIMARY KEY (Email),
	FOREIGN KEY (Email) REFERENCES PARTICIPANTE(Email)
);

CREATE TABLE INSTITUICAO(
	Nome VARCHAR(50) NOT NULL,
	Endereco VARCHAR(50) NOT NULL,

	PRIMARY KEY (Nome)
);

CREATE TABLE ESTUDANTE(
	Email VARCHAR(50) NOT NULL,
	Data_Inscricao VARCHAR(10) NOT NULL,
	Morada VARCHAR(50) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Instituicao VARCHAR(50) NOT NULL,

	PRIMARY KEY (Email),
	FOREIGN KEY (Email) REFERENCES PARTICIPANTE(Email),
	FOREIGN KEY (Instituicao) REFERENCES INSTITUICAO(Nome),
);

CREATE TABLE AUTOR(
	Email VARCHAR(50) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Instituicao VARCHAR(50) NOT NULL,

	PRIMARY KEY (Email),
	FOREIGN KEY (Instituicao) REFERENCES INSTITUICAO(Nome),
);