CREATE TABLE TURMA (
	ID INT NOT NULL,
	Designacao VARCHAR(20) NOT NULL,
	Ano_Letivo INT NOT NULL,
	Max_Alunos INT NOT NULL, 
	CHECK (Max_Alunos > 0),

	PRIMARY KEY (ID)
);

CREATE TABLE ATIVIDADE(
	ID VARCHAR(15) NOT NULL,
	Designacao VARCHAR(100) NOT NULL,
	Custo INT NOT NULL,

	PRIMARY KEY (ID),
);

CREATE TABLE PARTICIPA(
	ID_Atividade VARCHAR(15) NOT NULL,
	ID_Turma INT NOT NULL,

	PRIMARY KEY (ID_Atividade),
	FOREIGN KEY (ID_Atividade) REFERENCES ATIVIDADE(ID),
	FOREIGN KEY (ID_Turma) REFERENCES TURMA(ID),
);

CREATE TABLE ENC_EDUCACAO (
	CC VARCHAR(12) NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Morada VARCHAR(50) NOT NULL,
	Data_Nasc DATE NOT NULL,
	Telefone INT NOT NULL,
	CHECK (Telefone > 0 AND Telefone < 999999999),
	Email VARCHAR(25) NOT NULL,
	Relacao_com_Aluno VARCHAR(10) NOT NULL,

	PRIMARY KEY (CC),
);

CREATE TABLE PESSOA_AUTORIZADA(
	CC VARCHAR(12) NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Morada VARCHAR(50) NOT NULL,
	Data_Nasc DATE NOT NULL,
	Telefone INT NOT NULL,
	CHECK (Telefone > 0 AND Telefone < 999999999),
	Email VARCHAR(25) NOT NULL,
	Relacao_com_Aluno VARCHAR(10) NOT NULL,

	PRIMARY KEY (CC),
	
);

CREATE TABLE ALUNO(
	CC VARCHAR(12) NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Morada VARCHAR(50) NOT NULL,
	Data_Nasc DATE NOT NULL,
	Turma INT NOT NULL,
	ENC_EDUC_CC VARCHAR(12) NOT NULL,
	PESS_AUT_CC VARCHAR(12) NOT NULL,
	ATIVIDADES VARCHAR(15) NOT NULL,

	PRIMARY KEY (CC),
	FOREIGN KEY (Turma) REFERENCES TURMA(ID),
	FOREIGN KEY (ENC_EDUC_CC) REFERENCES ENC_EDUCACAO(CC),
	FOREIGN KEY (PESS_AUT_CC) REFERENCES PESSOA_AUTORIZADA(CC),
	FOREIGN KEY (ATIVIDADES) REFERENCES PARTICIPA(ID_Atividade),
	
);

CREATE TABLE PROFESSOR(
	CC VARCHAR(12) NOT NULL,
	Num_Funcionario INT NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Morada VARCHAR(50) NOT NULL,
	Data_Nasc DATE NOT NULL,
	Turma INT NOT NULL,

	PRIMARY KEY(CC, Num_Funcionario),
	FOREIGN KEY (Turma) REFERENCES TURMA(ID),
	
);